name: SVG to HTML PR

on:
  workflow_dispatch:
    inputs:
      svg_url:
        description: 'URL to CoreUI SVG file (.ts)'
        required: true
      icon_name:
        description: 'Icon name (used for HTML filename)'
        required: true
permissions:
  contents: write
  pull-requests: write

jobs:
  convert-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Download SVG file
        run: |
          mkdir -p svg-files
          curl -L -o svg-files/${{ github.event.inputs.icon_name }}.ts ${{ github.event.inputs.svg_url }}
          ls
          cat svg-files/${{ github.event.inputs.icon_name }}.ts
          
      - name: Convert SVG to HTML
        run: |
          go run scripts/svg-to-html.go ${{ github.workspace }}/svg-files/${{ github.event.inputs.icon_name }}.ts ${{ github.workspace }}/layouts/partials/content/svg/${{ github.event.inputs.icon_name }}.html
          cat ${{ github.workspace }}/layouts/partials/content/svg/${{ github.event.inputs.icon_name }}.html

      - name: Create branch, commit, and push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          branch_name=add-svg-${{ github.event.inputs.icon_name }}
          git checkout -b $branch_name
          git add layouts/partials/content/svg/${{ github.event.inputs.icon_name }}.html
          git commit -m "Add SVG partial for ${{ github.event.inputs.icon_name }}"
          git push origin $branch_name

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Add SVG partial: ${{ github.event.inputs.icon_name }}"
          branch: "add-svg-${{ github.event.inputs.icon_name }}"
          base: "main"
          body: |
            Automated SVG-to-HTML conversion for **${{ github.event.inputs.icon_name }}**.
